name: sphinx_ar
description: Flutter AR demo that tracks a Sphinx face and renders 3D content.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ar_flutter_plugin_plus: ^1.1.2
  vector_math: ^2.1.4
  permission_handler: ^12.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
